spring:
  cloud:
    config:
      enabled: false
      server:
        native:
          search-locations: classpath:/configurations
  profiles:
    active: native

security:
  user:
    name: ${CONFIG_SERVER_USERNAME}
    password: ${CONFIG_SERVER_PASSWORD}
  ignored:
    - /health
